sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t pandemic/scheduler-web .
  - docker run -d pandemic/scheduler-web
  - docker ps -a
  - docker run pandemic/scheduler-web /bin/bash -c "bundle exec rspec"

script:
  - bundle exec rspec

notifications:
  email: false
